export const ICONS = {
  edit: "edit",
  delete: "delete",
  refresh: "refresh",
  menu: "menu",
  close: "close",
  loading: "progress_activity",
  arrowUp: "keyboard_arrow_up",
  arrowDown: "keyboard_arrow_down",
  metadata: "settings",
  database: "database",
  add: "add",
  chart: "insert_chart",
  stop: "stop",
  play: "play_arrow",
  robot: "robot_2",
  mec: "dns",
  arrowRight: "arrow_right_alt",
  arrowSplit: "arrow_split",
  checked: "check_box",
  error: "error",
  layers: "layers",
  adjust: "adjust",
  checkCircle: "check_circle",
  user: "person",
};
