import { InstanceListResponse } from "@/type/response/_instance";
import { SimulationType } from "@/type/response/_simulation";

const MOCK_SIMULATION_LIST: SimulationType[] = [
  {
    simulationId: 1,
    simulationName: "Instance 1",
    simulationDescription: "Description for instance 1",
    simulationCreatedAt: "2023-01-15",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 2,
    simulationName: "Instance 2",
    simulationDescription: "Description for instance 2",
    simulationCreatedAt: "2023-02-20",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 3,
    simulationName: "Instance 3",
    simulationDescription: "Description for instance 3",
    simulationCreatedAt: "2023-03-10",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 4,
    simulationName: "Instance 4",
    simulationDescription: "Description for instance 4",
    simulationCreatedAt: "2023-04-05",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 5,
    simulationName: "Instance 5",
    simulationDescription: "Description for instance 5",
    simulationCreatedAt: "2023-05-17",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 6,
    simulationName: "Instance 6",
    simulationDescription: "Description for instance 6",
    simulationCreatedAt: "2023-06-02",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 7,
    simulationName: "Instance 7",
    simulationDescription: "Description for instance 7",
    simulationCreatedAt: "2023-07-21",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 8,
    simulationName: "Instance 8",
    simulationDescription: "Description for instance 8",
    simulationCreatedAt: "2023-08-13",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 9,
    simulationName: "Instance 9",
    simulationDescription: "Description for instance 9",
    simulationCreatedAt: "2023-09-10",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 10,
    simulationName: "Instance 10",
    simulationDescription: "Description for instance 10",
    simulationCreatedAt: "2023-10-01",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 11,
    simulationName: "Instance 11",
    simulationDescription: "Description for instance 11",
    simulationCreatedAt: "2023-11-05",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 12,
    simulationName: "Instance 12",
    simulationDescription: "Description for instance 12",
    simulationCreatedAt: "2023-12-15",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 13,
    simulationName: "Instance 13",
    simulationDescription: "Description for instance 13",
    simulationCreatedAt: "2024-01-20",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 14,
    simulationName: "Instance 14",
    simulationDescription: "Description for instance 14",
    simulationCreatedAt: "2024-02-11",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 15,
    simulationName: "Instance 15",
    simulationDescription: "Description for instance 15",
    simulationCreatedAt: "2024-03-17",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 16,
    simulationName: "Instance 16",
    simulationDescription: "Description for instance 16",
    simulationCreatedAt: "2024-04-22",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 17,
    simulationName: "Instance 17",
    simulationDescription: "Description for instance 17",
    simulationCreatedAt: "2024-05-08",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 18,
    simulationName: "Instance 18",
    simulationDescription: "Description for instance 18",
    simulationCreatedAt: "2024-06-05",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 19,
    simulationName: "Instance 19",
    simulationDescription: "Description for instance 19",
    simulationCreatedAt: "2024-07-10",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 20,
    simulationName: "Instance 20",
    simulationDescription: "Description for instance 20",
    simulationCreatedAt: "2024-08-25",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 21,
    simulationName: "Instance 21",
    simulationDescription: "Description for instance 21",
    simulationCreatedAt: "2024-09-15",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 22,
    simulationName: "Instance 22",
    simulationDescription: "Description for instance 22",
    simulationCreatedAt: "2024-10-02",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 23,
    simulationName: "Instance 23",
    simulationDescription: "Description for instance 23",
    simulationCreatedAt: "2024-11-12",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 24,
    simulationName: "Instance 24",
    simulationDescription: "Description for instance 24",
    simulationCreatedAt: "2024-12-30",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 25,
    simulationName: "Instance 25",
    simulationDescription: "Description for instance 25",
    simulationCreatedAt: "2025-01-08",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 26,
    simulationName: "Instance 26",
    simulationDescription: "Description for instance 26",
    simulationCreatedAt: "2025-02-22",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 27,
    simulationName: "Instance 27",
    simulationDescription: "Description for instance 27",
    simulationCreatedAt: "2025-03-13",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 28,
    simulationName: "Instance 28",
    simulationDescription: "Description for instance 28",
    simulationCreatedAt: "2025-04-09",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 29,
    simulationName: "Instance 29",
    simulationDescription: "Description for instance 29",
    simulationCreatedAt: "2025-05-18",
    simulationStatus: "RUNNING",
  },
  {
    simulationId: 30,
    simulationName: "Instance 30",
    simulationDescription: "Description for instance 30",
    simulationCreatedAt: "2025-06-15",
    simulationStatus: "RUNNING",
  },
];

const MOCK_INSTANCE_LIST: InstanceListResponse = [
  {
    instanceId: 0,
    instanceName: "instance1",
    instanceDescription: "description1",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 1,
    instanceName: "instance2",
    instanceDescription: "description2",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 2,
    instanceName: "instance3",
    instanceDescription: "description3",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 3,
    instanceName: "instance4",
    instanceDescription: "description4",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 4,
    instanceName: "instance5",
    instanceDescription: "description5",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 5,
    instanceName: "instance6",
    instanceDescription: "description6",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 6,
    instanceName: "instance7",
    instanceDescription: "description7",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 7,
    instanceName: "instance8",
    instanceDescription: "description8",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 8,
    instanceName: "instance9",
    instanceDescription: "description9",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 9,
    instanceName: "instance10",
    instanceDescription: "description10",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 10,
    instanceName: "instance11",
    instanceDescription: "description11",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 11,
    instanceName: "instance12",
    instanceDescription: "description12",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 12,
    instanceName: "instance13",
    instanceDescription: "description13",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 13,
    instanceName: "instance14",
    instanceDescription: "description14",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 14,
    instanceName: "instance15",
    instanceDescription: "description15",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 15,
    instanceName: "instance16",
    instanceDescription: "description16",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 16,
    instanceName: "instance17",
    instanceDescription: "description17",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 17,
    instanceName: "instance18",
    instanceDescription: "description18",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 18,
    instanceName: "instance19",
    instanceDescription: "description19",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 19,
    instanceName: "instance20",
    instanceDescription: "description20",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 20,
    instanceName: "instance21",
    instanceDescription: "description21",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 21,
    instanceName: "instance22",
    instanceDescription: "description22",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 22,
    instanceName: "instance23",
    instanceDescription: "description23",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 23,
    instanceName: "instance24",
    instanceDescription: "description24",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 24,
    instanceName: "instance25",
    instanceDescription: "description25",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 25,
    instanceName: "instance26",
    instanceDescription: "description26",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 26,
    instanceName: "instance27",
    instanceDescription: "description27",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 27,
    instanceName: "instance28",
    instanceDescription: "description28",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 28,
    instanceName: "instance29",
    instanceDescription: "description29",
    instanceCreatedAt: "2024-11-22",
  },
  {
    instanceId: 29,
    instanceName: "instance30",
    instanceDescription: "description30",
    instanceCreatedAt: "2024-11-22",
  },
];

const MOCK_OPTION_LIST = [
  { label: "ID", value: "simulationId" },
  { label: "설명", value: "simulationDescription" },
  { label: "이름", value: "simulationName" },
  { label: "생성일", value: "simulationCreatedAt" },
  { label: "ID1", value: "id1" },
  { label: "설명", value: "description1" },
  { label: "이름", value: "name1" },
  { label: "생성일", value: "createdAt1" },
  { label: "ID", value: "id2" },
  { label: "설명", value: "description2" },
  { label: "이름", value: "name2" },
  { label: "생성일", value: "createdAt2" },
];

export { MOCK_SIMULATION_LIST, MOCK_OPTION_LIST, MOCK_INSTANCE_LIST };
