const MOCK_INSTANCE_LIST = [
  {
    id: 1,
    name: "Instance A",
    description: "First instance",
    createdAt: "2023-01-01",
  },
  {
    id: 2,
    name: "Instance B",
    description: "Second instance",
    createdAt: "2023-02-14",
  },
  {
    id: 3,
    name: "Instance C",
    description: "Third instance",
    createdAt: "2023-03-22",
  },
  {
    id: 4,
    name: "Instance D",
    description: "Fourth instance",
    createdAt: "2023-04-05",
  },
  {
    id: 5,
    name: "Instance E",
    description: "Fifth instance",
    createdAt: "2023-05-15",
  },
  {
    id: 6,
    name: "Instance F",
    description: "Sixth instance",
    createdAt: "2023-06-10",
  },
  {
    id: 7,
    name: "Instance G",
    description: "Seventh instance",
    createdAt: "2023-07-23",
  },
  {
    id: 8,
    name: "Instance H",
    description: "Eighth instance",
    createdAt: "2023-08-30",
  },
  {
    id: 9,
    name: "Instance I",
    description: "Ninth instance",
    createdAt: "2023-09-12",
  },
  {
    id: 10,
    name: "Instance J",
    description: "Tenth instance",
    createdAt: "2023-10-01",
  },
  {
    id: 11,
    name: "Instance K",
    description: "Eleventh instance",
    createdAt: "2023-11-15",
  },
  {
    id: 12,
    name: "Instance L",
    description: "Twelfth instance",
    createdAt: "2023-12-10",
  },
  {
    id: 13,
    name: "Instance M",
    description: "Thirteenth instance",
    createdAt: "2024-01-20",
  },
  {
    id: 14,
    name: "Instance N",
    description: "Fourteenth instance",
    createdAt: "2024-02-25",
  },
  {
    id: 15,
    name: "Instance O",
    description: "Fifteenth instance",
    createdAt: "2024-03-15",
  },
  {
    id: 16,
    name: "Instance P",
    description: "Sixteenth instance",
    createdAt: "2024-04-05",
  },
  {
    id: 17,
    name: "Instance Q",
    description: "Seventeenth instance",
    createdAt: "2024-05-25",
  },
  {
    id: 18,
    name: "Instance R",
    description: "Eighteenth instance",
    createdAt: "2024-06-10",
  },
  {
    id: 19,
    name: "Instance S",
    description: "Nineteenth instance",
    createdAt: "2024-07-01",
  },
  {
    id: 20,
    name: "Instance T",
    description: "Twentieth instance",
    createdAt: "2024-08-18",
  },
  {
    id: 21,
    name: "Instance U",
    description: "Twenty-first instance",
    createdAt: "2024-09-05",
  },
  {
    id: 22,
    name: "Instance V",
    description: "Twenty-second instance",
    createdAt: "2024-10-12",
  },
  {
    id: 23,
    name: "Instance W",
    description: "Twenty-third instance",
    createdAt: "2024-11-01",
  },
  {
    id: 24,
    name: "Instance X",
    description: "Twenty-fourth instance",
    createdAt: "2024-12-25",
  },
  {
    id: 25,
    name: "Instance Y",
    description: "Twenty-fifth instance",
    createdAt: "2025-01-10",
  },
  {
    id: 26,
    name: "Instance Z",
    description: "Twenty-sixth instance",
    createdAt: "2025-02-20",
  },
  {
    id: 27,
    name: "Instance AA",
    description: "Twenty-seventh instance",
    createdAt: "2025-03-30",
  },
  {
    id: 28,
    name: "Instance AB",
    description: "Twenty-eighth instance",
    createdAt: "2025-04-10",
  },
  {
    id: 29,
    name: "Instance AC",
    description: "Twenty-ninth instance",
    createdAt: "2025-05-22",
  },
  {
    id: 30,
    name: "Instance AD",
    description: "Thirtieth instance",
    createdAt: "2025-06-15",
  },
];

const MOCK_OPTION_LIST = [
  { label: "인스턴스 ID", value: "id" },
  { label: "설명", value: "description" },
  { label: "이름", value: "name" },
  { label: "생성일", value: "createdAt" },
];

export { MOCK_INSTANCE_LIST, MOCK_OPTION_LIST };
